let articles=[],site={},adminPin="";
const state={topic:"Alle",search:"",access:"all",level:"all",language:"all",type:"all",view:"current",sort:"newest"};
const $=s=>document.querySelector(s),api=()=>window.WISSEN_API_URL||"",today=()=>new Date().toISOString().slice(0,10),ageDays=d=>d?Math.floor((Date.now()-new Date(`${d}T00:00:00`))/86400000):0;
const TOPIC_GROUPS=[
 {id:"Reanimation",icon:"♥",cls:"reanimation",re:/reanimation|rosc|aed|bls|als|cardiac|kreislauf|wiederbeleb/i},
 {id:"Trauma",icon:"🩹",cls:"trauma",re:/trauma|blutung|tourniquet|becken|sht|verletz/i},
 {id:"Atemweg & Beatmung",icon:"🫁",cls:"airway",re:/airway|atemweg|beatmung|ventilat|intubat/i},
 {id:"Internistische Notfälle",icon:"🩺",cls:"intern",re:/intern|sepsis|schmerz|analges|kreislauf|kardio|stemi/i},
 {id:"Neurologie",icon:"🧠",cls:"neuro",re:/neuro|schlaganfall|stroke/i},
 {id:"Pädiatrie",icon:"🧸",cls:"paediatrie",re:/pädi|paedi|kind/i},
 {id:"Pharmakologie",icon:"💊",cls:"pharma",re:/pharm|medikament|analges|ketamin|fentanyl|morphin/i},
 {id:"Diagnostik & POCUS",icon:"▣",cls:"diagnostik",re:/diagnost|pocus|ultraschall|sonograph/i},
 {id:"Kommunikation & Ethik",icon:"💬",cls:"kommunikation",re:/kommunikation|ethik|sterben|decision|entscheid|clinical reasoning|patientenperspektive|crm|human factors/i},
 {id:"Organisation & Systeme",icon:"⚙",cls:"organisation",re:/organisation|system|rettungsdienst|leitstelle|logistik|versorgung|stadt-land|zeitinterval|digital|dokument|hems/i},
 {id:"Ausbildung & Qualität",icon:"🎓",cls:"ausbildung",re:/ausbildung|qualität|leitlinie|patientensicherheit|simulation|debrief/i},
 {id:"Mental Health & Personal",icon:"♥",cls:"mental",re:/mental|ptbs|personal|arbeitsmedizin|psych/i},
 {id:"Speziallagen",icon:"▲",cls:"spezial",re:/alpin|manv|katastroph|drohnen|first responder|ersthelfer|österreich|dach/i}
];
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function attr(s){return esc(s)}
async function fetchJson(path,fallback){try{const r=await fetch(api()?`${api()}${path}`:fallback,{cache:"no-store"});if(!r.ok)throw 0;return await r.json()}catch{return null}}
async function loadAll(){const [a,s]=await Promise.all([fetchJson("/articles","data/articles.json"),fetchJson("/site","data/site.json")]);if(a)articles=a;if(s)site=s;applySite();fillTypeFilter();renderAll();fillArticleSelect();fillSiteForm()}
function applySite(){document.title=site.title||"RD-Literatur";$("#siteTitle").textContent=site.title||"RD-Literatur";$("#siteSubtitle").textContent=site.subtitle||"Wissenschaft. Für den Einsatz. Gemeinsam besser.";$("#siteFooter").textContent=site.footer||"Open Knowledge für den Rettungsdienst";if(site.accent)document.documentElement.style.setProperty("--accent",site.accent)}
function isArchived(a){if(a.archived===true)return true;const d=a.activeSince||a.added;return !!d&&ageDays(d)>30}function activeItems(){return articles.filter(a=>!isArchived(a))}function archivedItems(){return articles.filter(isArchived)}function viewPool(){return state.view==="archive"?archivedItems():activeItems()}
function levelLabel(v){return v==="rs"?"RS":v==="nfs"?"NFS":"RS–NFS"}function langLabel(v){return v==="de"?"🇩🇪 Deutsch":v==="en"?"🇬🇧 Englisch":"Sprache offen"}function accessLabel(v){return v==="oa"?["🔓 Open Access","oa"]:v==="free"?["🔓 Freie Version","oa"]:["Paywall","pay"]}
function articleText(a){return [a.title,a.authors,a.journal,a.type,a.why,a.license,...(a.topics||[])].join(" ")}
function groupsFor(a){const text=articleText(a);return TOPIC_GROUPS.filter(g=>g.re.test(text))}function primaryGroup(a){return groupsFor(a)[0]||{id:"Notfallmedizin",icon:"✚",cls:"organisation"}}
function formatDate(d){if(!d)return"";const [y,m,day]=d.split("-");return `${day}.${m}.${y}`}
function metadataLine(a){const g=primaryGroup(a),[al]=accessLabel(a.access);const parts=[g.id,levelLabel(a.level),langLabel(a.language).replace(/^\S+\s/,""),al.replace(/^\S+\s/,"")];return parts.map(x=>`<span>${esc(x)}</span>`).join("")}
function card(a){const archived=isArchived(a),date=archived?(a.archiveDate||a.activeSince||a.added):(a.activeSince||a.added);const main=a.freeUrl||a.publisherUrl||(a.doi?`https://doi.org/${a.doi}`:"");const details=[a.type,a.license].filter(Boolean).join(" · ");return `<article class="card"><div class="card-top"><span class="status-label">${archived?"Archiv":"Aktuell"}</span><span class="card-date">${esc(formatDate(date))}</span></div><h3>${esc(a.title)}</h3>${a.why?`<p>${esc(a.why)}</p>`:""}<div class="meta-line">${metadataLine(a)}</div>${details?`<div class="detail-line">${esc(details)}</div>`:""}<div class="source-line">${esc(a.authors||"")}${a.journal?" · "+esc(a.journal):""}${a.year?" · "+a.year:""}</div><div class="card-actions">${main?`<a class="article-link" href="${attr(main)}" target="_blank" rel="noopener">Zum Artikel <span>↗</span></a>`:""}${a.publisherUrl&&a.freeUrl&&a.publisherUrl!==a.freeUrl?`<a class="secondary-link" href="${attr(a.publisherUrl)}" target="_blank" rel="noopener">Originalquelle</a>`:""}</div></article>`}
function renderTopics(){const pool=viewPool();const available=TOPIC_GROUPS.filter(g=>pool.some(a=>g.re.test(articleText(a))));if(state.topic!=="Alle"&&!available.some(g=>g.id===state.topic))state.topic="Alle";const all=[{id:"Alle",icon:"▦",cls:""},...available];$("#topics").innerHTML=all.map(g=>`<button class="topic-btn ${g.cls?`topic-${g.cls}`:""} ${state.topic===g.id?"active":""}" data-topic="${attr(g.id)}"><span class="topic-icon">${g.icon}</span><span>${esc(g.id)}</span></button>`).join("");document.querySelectorAll(".topic-btn").forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;renderTopics();renderCards()})}
function fillTypeFilter(){const types=[...new Set(articles.map(a=>a.type).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"de"));$("#typeFilter").innerHTML='<option value="all">Alle</option>'+types.map(t=>`<option value="${attr(t)}">${esc(t)}</option>`).join("");if(!types.includes(state.type))state.type="all";$("#typeFilter").value=state.type}
function filtered(){const q=state.search.toLowerCase().trim();let f=viewPool().filter(a=>{const topic=state.topic==="Alle"||groupsFor(a).some(g=>g.id===state.topic),access=state.access==="all"||a.access===state.access,level=state.level==="all"||(a.level||"rs-nfs")===state.level,language=state.language==="all"||a.language===state.language,type=state.type==="all"||a.type===state.type,hay=[articleText(a),levelLabel(a.level),langLabel(a.language)].join(" ").toLowerCase();return topic&&access&&level&&language&&type&&(!q||hay.includes(q))});if(state.sort==="title")f.sort((a,b)=>a.title.localeCompare(b.title,"de"));else if(state.sort==="year")f.sort((a,b)=>Number(b.year||0)-Number(a.year||0));else f.sort((a,b)=>((b.activeSince||b.added||"").localeCompare(a.activeSince||a.added||""))||Number(b.year||0)-Number(a.year||0));return f}
function renderCards(){const pool=viewPool(),f=filtered();$("#count").textContent=`${f.length} von ${pool.length} ${state.view==="archive"?"Archiv-Einträgen":"aktuellen Beiträgen"}`;$("#empty").style.display=f.length?"none":"block";$("#cards").innerHTML=f.map(card).join("")}
function renderViewSwitch(){const c=activeItems().length,a=archivedItems().length;$("#currentCount").textContent=`(${c})`;$("#archiveCount").textContent=`(${a})`;$("#currentViewBtn").classList.toggle("active",state.view==="current");$("#archiveViewBtn").classList.toggle("active",state.view==="archive");$("#navCurrent").classList.toggle("active",state.view==="current");$("#navArchive").classList.toggle("active",state.view==="archive");$("#archiveNotice").classList.toggle("hidden",state.view!=="archive");$("#listHeading").textContent=state.view==="archive"?"Archiv":"Aktuelle Literatur"}
function renderAll(){renderViewSwitch();renderTopics();renderCards()}
function setView(v){state.view=v;state.topic="Alle";renderAll();window.scrollTo({top:0,behavior:"smooth"})}
$("#search").oninput=e=>{state.search=e.target.value;renderCards()};$("#access").onchange=e=>{state.access=e.target.value;renderCards()};$("#level").onchange=e=>{state.level=e.target.value;renderCards()};$("#language").onchange=e=>{state.language=e.target.value;renderCards()};$("#typeFilter").onchange=e=>{state.type=e.target.value;renderCards()};$("#sort").onchange=e=>{state.sort=e.target.value;renderCards()};
$("#resetFilters").onclick=()=>{Object.assign(state,{topic:"Alle",search:"",access:"all",level:"all",language:"all",type:"all"});for(const id of ["search","access","level","language","typeFilter"]){const el=$("#"+id);el.value=id==="search"?"":"all"}renderTopics();renderCards()};
$("#currentViewBtn").onclick=()=>setView("current");$("#archiveViewBtn").onclick=()=>setView("archive");$("#navCurrent").onclick=()=>setView("current");$("#navArchive").onclick=()=>setView("archive");

function openPin(){adminPin="";$("#adminPinInput").value="";$("#pinStatus").textContent="";$("#pinModal").classList.remove("hidden");setTimeout(()=>$("#adminPinInput").focus(),30)}
$("#adminOpen").onclick=openPin;$("#pinCancel").onclick=()=>$("#pinModal").classList.add("hidden");$("#pinModal").onclick=e=>{if(e.target.id==="pinModal")$("#pinModal").classList.add("hidden")};
// Die PIN wird beim Öffnen abgefragt und bei jeder schreibenden Worker-Anfrage serverseitig geprüft.
// So funktioniert das Fenster auch mit älteren Worker-Versionen ohne separate /auth-Route.
$("#pinForm").onsubmit=e=>{e.preventDefault();const pin=$("#adminPinInput").value.trim();if(!pin)return;adminPin=pin;$("#pinModal").classList.add("hidden");$("#adminModal").classList.remove("hidden")};
$("#adminClose").onclick=()=>{adminPin="";$("#adminModal").classList.add("hidden")};$("#adminModal").onclick=e=>{if(e.target.id==="adminModal"){adminPin="";$("#adminModal").classList.add("hidden")}};
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===t));document.querySelectorAll(".tabpane").forEach(p=>p.classList.add("hidden"));$("#"+t.dataset.tab).classList.remove("hidden")});
function fillArticleSelect(){const sel=$("#articleSelect");sel.innerHTML='<option value="">Neuen Artikel anlegen</option>'+articles.slice().sort((a,b)=>a.title.localeCompare(b.title,"de")).map(a=>`<option value="${attr(a.id)}">${isArchived(a)?"[Archiv] ":""}${esc(a.title)}</option>`).join("")}
function resetArticle(){const f=$("#articleForm");f.reset();f.elements.id.value="";f.elements.level.value="rs-nfs";f.elements.language.value="de";$("#deleteBtn").classList.add("hidden");$("#archiveToggleBtn").classList.add("hidden");$("#formStatus").textContent="";$("#articleSelect").value=""}$("#newArticleBtn").onclick=resetArticle;
$("#articleSelect").onchange=e=>{const a=articles.find(x=>x.id===e.target.value);if(!a)return resetArticle();const f=$("#articleForm");for(const k of ["id","title","authors","journal","year","doi","type","read","access","publisherUrl","freeUrl","why","level","language","license"])if(f.elements[k])f.elements[k].value=a[k]??(k==="level"?"rs-nfs":k==="language"?"de":"");f.elements.topics.value=(a.topics||[]).join(", ");f.elements.featured.checked=!!a.featured;$("#deleteBtn").classList.remove("hidden");const b=$("#archiveToggleBtn");b.classList.remove("hidden");b.textContent=isArchived(a)?"↩ Aus Archiv auf Startseite":"📦 Ins Archiv verschieben"};
$("#doiBtn").onclick=async()=>{let doi=$("#doiLookup").value.trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,"");if(!doi)return;$("#formStatus").textContent="DOI wird abgefragt …";try{const r=await fetch(`https://api.crossref.org/works/${encodeURIComponent(doi)}`);if(!r.ok)throw new Error("DOI nicht gefunden");const m=(await r.json()).message,f=$("#articleForm");f.elements.title.value=(m.title&&m.title[0])||"";f.elements.authors.value=(m.author||[]).map(a=>[a.given,a.family].filter(Boolean).join(" ")).join(", ");f.elements.journal.value=(m["container-title"]&&m["container-title"][0])||m.publisher||"";const parts=(m.published&&m.published["date-parts"]&&m.published["date-parts"][0])||(m.issued&&m.issued["date-parts"]&&m.issued["date-parts"][0]);f.elements.year.value=parts?parts[0]:"";f.elements.doi.value=m.DOI||doi;f.elements.publisherUrl.value=m.URL||`https://doi.org/${doi}`;$("#formStatus").textContent="Metadaten übernommen. Bitte die redaktionellen Felder ergänzen."}catch(err){$("#formStatus").textContent="DOI-Abfrage fehlgeschlagen: "+err.message}};
function formArticle(fd){const existing=fd.get("id"),old=articles.find(a=>a.id===existing),slug=(fd.get("title")||"artikel").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");return{id:existing||`${slug}-${Date.now()}`,title:fd.get("title").trim(),authors:fd.get("authors").trim(),journal:fd.get("journal").trim(),year:Number(fd.get("year"))||"",doi:fd.get("doi").trim(),topics:fd.get("topics").split(",").map(x=>x.trim()).filter(Boolean),type:fd.get("type"),level:fd.get("level")||"rs-nfs",language:fd.get("language")||"de",license:fd.get("license").trim(),read:fd.get("read").trim(),access:fd.get("access"),why:fd.get("why").trim(),publisherUrl:fd.get("publisherUrl").trim(),freeUrl:fd.get("freeUrl").trim(),featured:fd.get("featured")==="on",added:old?.added||today(),activeSince:old?.activeSince||today(),archived:old?.archived||false,archiveDate:old?.archiveDate||""}}
async function saveArticle(article,statusText="Gespeichert."){if(!api()){$("#formStatus").textContent="Speichern ist erst nach Einrichtung des Workers aktiv.";return false}try{const exists=articles.some(a=>a.id===article.id),r=await fetch(`${api()}/articles`,{method:exists?"PUT":"POST",headers:{"Content-Type":"application/json","X-Admin-Pin":adminPin},body:JSON.stringify(article)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Fehler");await loadAll();$("#formStatus").textContent=statusText;return true}catch(err){$("#formStatus").textContent="Fehler: "+err.message;return false}}
$("#previewBtn").onclick=()=>{const a=formArticle(new FormData($("#articleForm")));$("#cards").innerHTML=card(a)+$("#cards").innerHTML;$("#adminModal").classList.add("hidden");window.scrollTo({top:document.querySelector("#cards").offsetTop-120,behavior:"smooth"})};
$("#articleForm").onsubmit=async e=>{e.preventDefault();$("#formStatus").textContent="Speichere …";const ok=await saveArticle(formArticle(new FormData(e.target)));if(ok)resetArticle()};
$("#archiveToggleBtn").onclick=async()=>{const id=$("#articleForm").elements.id.value,a=articles.find(x=>x.id===id);if(!a)return;const archived=isArchived(a),next={...a,archived:!archived,archiveDate:archived?"":today(),activeSince:archived?today():(a.activeSince||a.added||today()),featured:archived?a.featured:false};$("#formStatus").textContent=archived?"Hole Artikel zurück …":"Verschiebe ins Archiv …";const ok=await saveArticle(next,archived?"Artikel ist zurück auf der Startseite. Der 30-Tage-Timer wurde neu gestartet.":"Artikel wurde ins Archiv verschoben.");if(ok){$("#articleSelect").value=id;$("#articleSelect").dispatchEvent(new Event("change"))}};
$("#deleteBtn").onclick=async()=>{const id=$("#articleForm").elements.id.value;if(!id||!confirm("Diesen Artikel wirklich löschen?"))return;if(!api()){$("#formStatus").textContent="Löschen ist erst nach Einrichtung des Workers aktiv.";return}try{const r=await fetch(`${api()}/articles/${encodeURIComponent(id)}`,{method:"DELETE",headers:{"X-Admin-Pin":adminPin}}),d=await r.json();if(!r.ok)throw new Error(d.error||"Fehler");await loadAll();resetArticle();$("#formStatus").textContent="Artikel gelöscht."}catch(err){$("#formStatus").textContent="Fehler: "+err.message}};
function fillSiteForm(){const f=$("#siteForm");for(const k of ["title","eyebrow","subtitle","footer","accent"])if(f.elements[k])f.elements[k].value=site[k]||""}
$("#siteForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),next={title:fd.get("title").trim(),eyebrow:fd.get("eyebrow").trim(),subtitle:fd.get("subtitle").trim(),footer:fd.get("footer").trim(),accent:fd.get("accent")};if(!api()){site=next;applySite();$("#siteStatus").textContent="Vorschau angewendet. Dauerhaftes Speichern benötigt den Worker.";return}try{const r=await fetch(`${api()}/site`,{method:"PUT",headers:{"Content-Type":"application/json","X-Admin-Pin":adminPin},body:JSON.stringify(next)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Fehler");site=next;applySite();$("#siteStatus").textContent="Erscheinungsbild gespeichert."}catch(err){$("#siteStatus").textContent="Fehler: "+err.message}};
if(window.matchMedia("(min-width: 801px)").matches)$("#filterDetails")?.setAttribute("open","");
loadAll();
