(()=>{
const page=document.body.dataset.page||'home',API=(window.WISSEN_API_URL||'').replace(/\/$/,''),LS='ost1020-v31-',D=window.OST1020_DATA||{};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const clone=v=>JSON.parse(JSON.stringify(v??[])),arr=v=>Array.isArray(v)?v:String(v||'').split(/\n|;/).map(s=>s.trim()).filter(Boolean);
const svg={
 menu:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16"/></svg>`,
 home:`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/></svg>`,
 books:`<svg viewBox="0 0 64 64"><rect x="10" y="38" width="44" height="10" rx="3" fill="#2f80ed"/><rect x="14" y="27" width="40" height="9" rx="3" fill="#68adf8"/><rect x="10" y="15" width="39" height="10" rx="3" fill="#8bc4ff"/><path d="M18 18h24M20 30h27M17 41h30" stroke="#fff" stroke-width="2.5" stroke-linecap="round"/></svg>`,
 abcde:`<svg viewBox="0 0 64 64"><rect x="7" y="9" width="50" height="46" rx="14" fill="#eef6ff"/><path d="M14 17h17M14 25h17M14 33h17M14 41h17M14 49h17" stroke-width="6" stroke-linecap="round"/><path d="M40 17c6 5 8 11 8 19 0 7-2 12-8 17" fill="none" stroke="#73aef0" stroke-width="4"/></svg>`,
 diag:`<svg viewBox="0 0 64 64" fill="none"><path d="M16 17v14c0 10 7 16 16 16s16-6 16-16V17" stroke="#2f80ed" stroke-width="4" stroke-linecap="round"/><circle cx="16" cy="15" r="5" fill="#2f80ed"/><circle cx="48" cy="15" r="5" fill="#2f80ed"/><circle cx="32" cy="48" r="8" stroke="#2f80ed" stroke-width="4"/></svg>`,
 skill:`<svg viewBox="0 0 64 64" fill="none"><path d="M14 36c8-8 9-16 10-21 1-4 7-4 8 1l1 9 4-12c1-4 7-4 8 0l2 13" stroke="#2f80ed" stroke-width="5" stroke-linecap="round"/><path d="M14 45h36" stroke="#7bb9ff" stroke-width="5" stroke-linecap="round"/></svg>`,
 alg:`<svg viewBox="0 0 64 64" fill="none"><rect x="13" y="8" width="38" height="48" rx="8" fill="#eef6ff" stroke="#2f80ed" stroke-width="3"/><path d="M21 20h20M21 29h13M21 38h18" stroke="#2f80ed" stroke-width="3" stroke-linecap="round"/><circle cx="46" cy="42" r="9" fill="#24b47e"/><path d="m42 42 3 3 5-6" stroke="#fff" stroke-width="2.6" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
 sim:`<svg viewBox="0 0 64 64" fill="none"><rect x="7" y="10" width="50" height="34" rx="9" fill="#29455f"/><path d="M12 29h8l5-10 7 18 6-13 5 5h8" stroke="#43d3c6" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><circle cx="25" cy="49" r="9" fill="#2f80ed"/><path d="m22 44 7 5-7 5z" fill="#fff"/></svg>`,
 calendar:`<svg viewBox="0 0 64 64" fill="none"><rect x="9" y="13" width="46" height="42" rx="10" fill="#efe7ff" stroke="#7b55df" stroke-width="3"/><path d="M9 25h46M20 8v10M44 8v10" stroke="#7b55df" stroke-width="4" stroke-linecap="round"/><circle cx="22" cy="35" r="3" fill="#7b55df"/><circle cx="32" cy="35" r="3" fill="#7b55df"/><circle cx="42" cy="35" r="3" fill="#7b55df"/></svg>`,
 change:`<svg viewBox="0 0 64 64" fill="none"><rect x="12" y="8" width="40" height="48" rx="8" fill="#f7edff" stroke="#c257c8" stroke-width="3"/><path d="M21 20h22M21 29h18M21 38h20" stroke="#c257c8" stroke-width="3" stroke-linecap="round"/></svg>`
};
function icon(name){return svg[name]||svg.books}
function chrome(){
 const mb=$('[data-menu-btn]'),hb=$('[data-home-btn]');if(mb)mb.innerHTML=svg.menu;if(hb)hb.innerHTML=svg.home;
 const groups=[
  ['Nachschlagen',[['literatur.html','📚','Literatur','article'],['abcde.html','🩺','ABCDE','abcde'],['differential.html','🔎','Differentialdiagnostik','diff'],['skilltraining.html','🎓','Skilltraining','skill'],['algorithmen.html','📋','Algorithmen & Leitlinien','alg']]],
  ['Aktuell & Organisation',[['aktuelles.html','📣','Aktuelles','news'],['lehrmeinung.html','🔄','Lehrmeinungsänderungen','change'],['termine.html','📅','Termine','events']]],
  ['Simulation & Material',[['simulation.html','🖥️','Simulationstraining','sim'],['materialien.html','📁','Materialien','materials']]],
  ['Verwalten',[['editor.html','✏️','Redaktion','editor']]]
 ];
 document.body.insertAdjacentHTML('beforeend',`<div class="menu"><div class="shade" data-menu-close></div><aside class="menu-sheet"><div class="menu-head"><div><span class="menu-eyebrow">OST 1020</span><strong>Bereiche</strong></div><button class="close" data-menu-close>✕</button></div>${groups.map((g,gi)=>`<section class="menu-group"><div class="nav-section">${g[0]}</div><nav class="nav">${g[1].map((x,i)=>`<a href="${x[0]}" class="nav-${x[3]} ${page===({article:'literature',abcde:'abcde',diff:'differential',skill:'skills',alg:'algorithms',news:'news',change:'changes',events:'events',sim:'guide',materials:'materials',editor:'editor'}[x[3]])?'active':''}"><span class="nav-icon">${x[1]}</span><span class="nav-copy"><strong>${x[2]}</strong></span><span class="nav-arrow">›</span></a>`).join('')}</nav></section>`).join('')}</aside></div><div class="overlay"><div class="shade" data-overlay-close></div><section class="overlay-panel" role="dialog" aria-modal="true"><div class="overlay-head"><h2 data-overlay-title></h2><button class="close" data-overlay-close>✕</button></div><div class="overlay-body" data-overlay-body></div></section></div>`);
 const showMenu=()=>$('.menu').classList.add('show');
 if(mb)mb.onclick=showMenu;
 $$('[data-menu-close]').forEach(x=>x.onclick=()=>$('.menu').classList.remove('show'));
 $$('[data-overlay-close]').forEach(x=>x.onclick=()=>$('.overlay').classList.remove('show'));
 document.addEventListener('click',e=>{const hm=e.target.closest('[data-hero-menu]');if(hm){e.preventDefault();showMenu()}});
}
function open(title,html){
 $('[data-overlay-title]').textContent=title;
 $('[data-overlay-body]').innerHTML=html;
 $('.overlay').classList.add('show');
}
async function get(name){if(API){try{const r=await fetch(`${API}/content/${name}`,{cache:'no-store'});if(r.ok)return await r.json()}catch(e){}}try{const l=localStorage.getItem(LS+name);if(l)return JSON.parse(l)}catch(e){}return clone(D[name]||[])}
async function articles(){if(API){try{const r=await fetch(`${API}/articles`,{cache:'no-store'});if(r.ok)return await r.json()}catch(e){}}return clone(D.articles||[])}
async function save(name,data){
 localStorage.setItem(LS+name,JSON.stringify(data));
 if(API){try{const url=`${API}/content/${name}`;const r=await fetch(url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return r.ok}catch(e){}}
 return false
}

function coreCard(href,ico,title,sub){return `<a class="core-card" href="${href}"><div class="core-visual">${ico}</div><div><h3>${title}</h3><p>${sub}</p></div><span class="core-arrow">›</span></a>`}
function newsHtml(n){const map={Lehrmeinung:'🔄',Leitlinie:'📋',Ausbildung:'🎓',Termin:'📅',Simulationstraining:'🖥️',Organisation:'📣',Literatur:'📚'};const c=n.category||'Organisation';return `<article class="news-item"><span class="news-icon">${map[c]||'📣'}</span><div><span class="cat-pill">${esc(c)}</span><h3>${esc(n.title)}</h3><div class="news-meta">${esc(n.date||'')}</div>${n.text?`<div class="news-text">${esc(n.text)}</div>`:''}</div><span class="arrow">›</span></article>`}
async function home(){
 const [news,events]=await Promise.all([get('news'),get('events')]);
 const now=new Date(),today=now.toISOString().slice(0,10),active=(news||[]).filter(x=>x.active!==false).slice(0,3);
 const upcoming=(events||[]).filter(x=>x.date>=today).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,3);
 const monday=new Date(now);monday.setHours(12,0,0,0);monday.setDate(now.getDate()-((now.getDay()+6)%7));
 const week=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const key=d.toISOString().slice(0,10),hits=(events||[]).filter(e=>e.date===key);return {d,key,hits}});
 const weekHtml=week.map(({d,key,hits})=>`<a class="week-day ${key===today?'today':''} ${hits.length?'has-event':''}" href="termine.html"><span>${d.toLocaleDateString('de-DE',{weekday:'short'}).replace('.','')}</span><strong>${d.getDate()}</strong>${hits.length?`<em>${hits.length}</em>`:''}</a>`).join('');
 const eventHtml=upcoming.map(e=>{const count=arr(e.attendees).length,cap=Number(e.capacity)||10;return `<a class="week-event" href="termine.html"><span class="week-event-date">${new Date(e.date+'T12:00:00').toLocaleDateString('de-DE',{day:'2-digit',month:'short'})}</span><span class="week-event-copy"><strong>${esc(e.title)}</strong><small>${esc(e.time||'')} · ${esc(e.location||'')}</small></span><span class="week-event-count">👥 ${count}/${cap}</span></a>`}).join('')||'<div class="empty compact">Keine Termine in nächster Zeit.</div>';
 $('[data-main]').innerHTML=`<section class="dashboard-hero compact-hero"><div class="hero-controls"><button class="hero-control" data-hero-menu aria-label="Menü">${svg.menu}</button><a class="hero-control home-control" href="index.html" aria-label="Startseite">${svg.home}</a></div><div class="hero-kicker">OST 1020</div><h1>Wissenssammlung 1020</h1></section>
 <section class="section section-first"><div class="section-head"><h2>Aktuelles</h2><a href="aktuelles.html">Alle anzeigen</a></div><div class="news-list dashboard-news">${active.map(newsHtml).join('')||'<div class="empty">Keine Meldungen</div>'}</div></section>
 <section class="section"><div class="section-head"><h2>Diese Woche</h2><a href="termine.html">Kalender öffnen</a></div><div class="week-card"><div class="week-strip">${weekHtml}</div><div class="week-events">${eventHtml}</div></div></section>
 <section class="section"><div class="section-head"><h2>Schnellzugriff</h2></div><div class="core-grid">${coreCard('literatur.html',svg.books,'Literatursammlung','Lehrbücher, Artikel und Leitlinien')}${coreCard('abcde.html',svg.abcde,'ABCDE-Schema','Systematisch beurteilen und handeln')}${coreCard('differential.html',svg.diag,'Differentialdiagnostik','Symptome einordnen und abgrenzen')}${coreCard('skilltraining.html',svg.skill,'Skilltraining','Praktische Fertigkeiten Schritt für Schritt')}${coreCard('algorithmen.html',svg.alg,'Algorithmen & Leitlinien','Handlungssicherheit in jeder Situation')}${coreCard('simulation.html',svg.sim,'Simulationstraining','Szenarien, Funktionen und Tipps')}${coreCard('termine.html',svg.calendar,'Termine','Übungen und Fortbildungen')}${coreCard('lehrmeinung.html',svg.change,'Lehrmeinungsänderungen','Neue Empfehlungen kompakt')}</div></section>`
}
async function newsPage(){const d=await get('news');$('[data-main]').innerHTML=`<section class="page-banner"><h1>Aktuelles</h1><div class="toolbar"><div class="filter-chips"><button class="filter-chip active" data-cat="all">Alle</button>${[...new Set(d.map(x=>x.category||'Organisation'))].map(c=>`<button class="filter-chip" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div></div></section><div class="news-list" data-list></div>`;const draw=cat=>{$('[data-list]').innerHTML=d.filter(x=>cat==='all'||(x.category||'Organisation')===cat).map(newsHtml).join('')};$('[data-main]').onclick=e=>{const b=e.target.closest('[data-cat]');if(!b)return;$$('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.cat)};draw('all')}
async function literature(){
 const arts=await articles();
 const defs=[['Reanimation','❤️',['Reanimation','Kreislaufstillstand']],['Simulation & Debriefing','👥',['Simulation','Debriefing','Ausbildung']],['CRM & Human Factors','🧑‍🤝‍🧑',['CRM','Human Factors','Entscheidungsfindung']],['Neurologie / Schlaganfall','🧠',['Neurologie','Schlaganfall']],['Qualität & Sicherheit','🛡️',['Qualität','Patientensicherheit','System']],['Critical Care','🫁',['Critical Care','Diagnostik']],['Pharmakologie & Schmerz','💊',['Pharmakologie','Schmerz']],['HEMS & Präklinik','🚁',['HEMS','Versorgung','Österreich']]];
 const now=new Date();const fresh=a=>{const raw=a.added||a.activeSince||'';if(!raw)return false;const d=new Date(raw+'T12:00:00');return !Number.isNaN(d.getTime())&&((now-d)/86400000)<=30&&((now-d)/86400000)>=0};
 const freshItems=arts.filter(fresh);
 const groups=[{id:'new',title:'Neuerscheinungen',icon:'✨',items:freshItems,new:true},...defs.map((x,i)=>({id:'g'+i,title:x[0],icon:x[1],items:arts.filter(a=>arr(a.topics).some(t=>x[2].includes(t)))}))].filter(g=>g.items.length);
 $('[data-main]').innerHTML=`<section class="page-banner lit-banner"><div class="page-banner-row"><h1>Literatursammlung</h1><a class="editor-shortcut" href="editor.html#literatur">✏️ Redaktion</a></div><div class="toolbar"><div class="searchbar"><input data-q placeholder="Literatur suchen …"><select data-f><option value="all">Alle Kategorien</option>${groups.map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join('')}</select></div><div class="filter-chips"><button class="filter-chip active" data-chip="all">Alle</button>${groups.map(g=>`<button class="filter-chip" data-chip="${g.id}">${g.icon} ${esc(g.title)}</button>`).join('')}</div></div></section><section class="lit-list" data-list></section>`;
 function article(a){const link=a.freeUrl||a.publisherUrl||'';const auth=Array.isArray(a.authors)?a.authors.join(', '):String(a.authors||'');return `<article class="lit-article-card"><div class="doc-icon">📄</div><div class="lit-article-copy"><h4>${esc(a.title)}</h4><p>${esc(auth)}${a.journal?` · ${esc(a.journal)}`:''}${a.year?` · ${esc(a.year)}`:''}</p><div class="lit-meta"><span class="meta-chip">${esc(a.type||'Artikel')}</span>${a.level?`<span class="meta-chip">${esc(String(a.level).toUpperCase())}</span>`:''}${a.access?`<span class="meta-chip">${esc(a.access==='oa'?'Open Access':a.access==='free'?'Freie Version':'Paywall')}</span>`:''}</div></div>${link?`<a class="circle-arrow" href="${esc(link)}" target="_blank" rel="noopener">›</a>`:''}</article>`}
 function draw(){const q=$('[data-q]').value.toLowerCase().trim(),fid=$('[data-f]').value;const list=groups.filter(g=>fid==='all'||g.id===fid).map(g=>{const items=g.items.filter(a=>!q||[a.title,Array.isArray(a.authors)?a.authors.join(' '):a.authors,a.journal,arr(a.topics).join(' ')].join(' ').toLowerCase().includes(q));if(!items.length)return'';return `<article class="lit-topic" data-group="${g.id}"><button class="lit-topic-head" data-toggle="${g.id}"><span class="lit-topic-icon">${g.icon}</span><span><h3>${esc(g.title)}</h3><p>${items.length} Artikel${g.new?' · letzte 30 Tage':''}</p></span><span class="circle-arrow">›</span></button><div class="lit-articles hidden">${items.map(article).join('')}</div></article>`}).join('');$('[data-list]').innerHTML=list||'<div class="empty">Keine Treffer</div>'}
 $('[data-q]').oninput=draw;$('[data-f]').onchange=draw;$('[data-main]').onclick=e=>{const c=e.target.closest('[data-chip]');if(c){$$('[data-chip]').forEach(x=>x.classList.toggle('active',x===c));$('[data-f]').value=c.dataset.chip;draw();return}const t=e.target.closest('[data-toggle]');if(t){const box=t.closest('.lit-topic'),body=$('.lit-articles',box);box.classList.toggle('expanded');body.classList.toggle('hidden');$('.circle-arrow',t).textContent=body.classList.contains('hidden')?'›':'⌃'}};draw()
}
async function abcdePage(){
 const d=await get('abcde'),labels={A:'Airway',B:'Breathing',C:'Circulation',D:'Disability',E:'Exposure'},sub={A:'Atemweg',B:'Atmung',C:'Kreislauf',D:'Neurologie',E:'Umgebung'},vis={A:'🫁',B:'🫁',C:'❤️',D:'🧠',E:'🌡️'};let current=0;
 $('[data-main]').innerHTML=`<section class="page-banner compact-banner"><h1>ABCDE-Schema</h1></section><section class="abcde-wrap"><div class="abcde-tabs" data-tabs></div><div class="abcde-main simplified" data-detail></div></section>`;
 function block(title,ico,items,klass=''){return `<section class="abcde-block ${klass}"><div class="abcde-block-head"><span>${ico}</span><strong>${title}</strong></div><ul>${arr(items).map(it=>`<li>${esc(it)}</li>`).join('')}</ul></section>`}
 function render(){const x=d[current];$('[data-tabs]').innerHTML=d.map((a,i)=>`<button class="abcde-tab ${a.key.toLowerCase()} ${i===current?'active':''}" data-abc="${i}"><strong>${esc(a.key)}</strong><span>${esc(labels[a.key]||a.title)}</span></button>`).join('');$('[data-detail]').innerHTML=`<div class="abcde-head"><span class="abcde-letter">${esc(x.key)}</span><span><h2>${esc(x.key)} – ${esc(labels[x.key]||x.title)}</h2><p>${esc(sub[x.key]||x.title)}</p></span><span class="abcde-visual">${vis[x.key]||'🩺'}</span></div><div class="abcde-direct">${block('Beurteilung','🔎',x.checks)}${block('Maßnahmen','⚙️',x.actions)}${block('Warnzeichen','⚠️',x.pitfalls,'warning')}</div>`}
 $('[data-main]').onclick=e=>{const a=e.target.closest('[data-abc]');if(a){current=+a.dataset.abc;render()}};render()
}
async function simpleCards(name,title,mode){
 const d=await get(name);const emo={lungs:'🫁',heart:'❤️',brain:'🧠',bolt:'⚡',abdomen:'🩺',syringe:'💉',clock:'🕒',bandage:'🩹',stethoscope:'🩺',search:'🔎'};
 $('[data-main]').innerHTML=`<section class="page-banner"><h1>${title}</h1></section><div class="list">${d.map((x,i)=>`<button class="row-card" data-i="${i}"><span class="row-icon">${mode==='diff'?(emo[x.icon]||x.icon||'🩺'):esc(x.icon|| (mode==='change'?'🔄':mode==='guide'?'🖥️':'📋'))}</span><span><strong>${esc(x.title||x.name)}</strong><small>${esc(x.category||x.stand||'')}</small></span><span class="arrow">›</span></button>`).join('')}</div>`;
 $('[data-main]').onclick=e=>{const b=e.target.closest('[data-i]');if(!b)return;const x=d[+b.dataset.i];let html='';if(mode==='diff')html=`<section class="overlay-section"><h3>Mögliche Ursachen</h3>${arr(x.causes).map(v=>`<button class="overlay-row"><span class="oi">🔎</span><span><strong>${esc(v)}</strong></span><span class="arrow">›</span></button>`).join('')}</section><section class="overlay-section"><h3>Wichtige Fragen</h3><ul>${arr(x.questions).map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section><section class="overlay-section warning"><h3>Red Flags</h3><ul>${arr(x.redflags).map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section>`;else if(mode==='alg')html=`<section class="overlay-section"><h3>Ablauf</h3><ul>${arr(x.steps).map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section><section class="overlay-section"><h3>Quelle</h3><div class="news-text">${esc(x.source||'')}</div></section>`;else if(mode==='change')html=`<section class="overlay-section"><h3>Bisher</h3><div class="news-text">${esc(x.old||'')}</div></section><section class="overlay-section"><h3>Neu</h3><div class="news-text">${esc(x.new||'')}</div></section><section class="overlay-section"><h3>Quelle</h3><div class="news-text">${esc(x.source||'')}</div></section>`;else if(mode==='guide')html=`<section class="overlay-section"><h3>Schritte</h3><ul>${arr(x.steps).map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section>`;else html=`<section class="overlay-section"><div class="news-text">${esc(x.note||x.description||'')}</div></section>`;open(x.title||x.name,html)}
}
async function skills(){const d=await get('skills');$('[data-main]').innerHTML=`<section class="page-banner"><h1>Skilltraining</h1></section><section class="skill-groups">${d.map((g,gi)=>`<div><div class="skill-group-head"><h2>${esc(g.name)}</h2><span>${g.skills.length} Skills</span></div><div class="skill-grid">${g.skills.map((s,si)=>`<button class="skill-card" data-g="${gi}" data-s="${si}"><span class="skill-icon">${si%5===0?'🫁':si%5===1?'🩺':si%5===2?'❤️':si%5===3?'🧰':'🩹'}</span><span><strong>${esc(s.name)}</strong><small>${s.items.length} Checkpunkte</small></span><span class="arrow">›</span></button>`).join('')}</div></div>`).join('')}</section>`;$('[data-main]').onclick=e=>{const b=e.target.closest('[data-g][data-s]');if(!b)return;const s=d[+b.dataset.g].skills[+b.dataset.s],steps=arr(s.items);open(s.name,`<div class="overlay-tabs"><button class="overlay-tab active" data-st="guide">Anleitung</button><button class="overlay-tab" data-st="material">Material</button><button class="overlay-tab" data-st="tips">Praxis-Tipps</button></div><div data-skill-body><section class="overlay-section"><h3>Ablauf</h3>${steps.map((x,i)=>`<button class="overlay-row"><span class="oi">${i+1}</span><span><strong>${esc(x)}</strong></span><span class="arrow">›</span></button>`).join('')}</section></div>`);$('.overlay-body').onclick=ev=>{const tab=ev.target.closest('[data-st]');if(!tab)return;$$('[data-st]').forEach(x=>x.classList.toggle('active',x===tab));const box=$('[data-skill-body]');if(tab.dataset.st==='guide')box.innerHTML=`<section class="overlay-section"><h3>Ablauf</h3>${steps.map((x,i)=>`<button class="overlay-row"><span class="oi">${i+1}</span><span><strong>${esc(x)}</strong></span><span class="arrow">›</span></button>`).join('')}</section>`;if(tab.dataset.st==='material')box.innerHTML=`<section class="overlay-section"><h3>Material</h3><div class="news-text">Material gemäß lokalem Ausbildungsstandard und eingesetztem Gerätesystem vorbereiten.</div></section>`;if(tab.dataset.st==='tips')box.innerHTML=`<section class="overlay-section"><h3>Praxis-Tipps</h3><div class="news-text">Ablauf strukturiert durchführen, Teamkommunikation beachten und Ergebnis anschließend kontrollieren.</div></section>`}}}
function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function dayKey(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
async function toggleRsvp(eventId,clientId){if(API){try{const r=await fetch(`${API}/events/rsvp/${encodeURIComponent(eventId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId})});if(r.ok)return await r.json()}catch(e){}}return null}
async function eventsPage(){let d=await get('events');let cursor=new Date();cursor.setDate(1);let selected='';const clientId=localStorage.getItem('ost1020-client-id')||(()=>{const id='c-'+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem('ost1020-client-id',id);return id})();$('[data-main]').innerHTML=`<section class="page-banner"><h1>Termine</h1></section><section class="calendar" data-cal></section><section class="section"><div class="section-head"><h2 data-list-title>Kommende Termine</h2></div><div class="event-list" data-events></div></section>`;
 function drawCal(){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),off=(first.getDay()+6)%7,prevDays=new Date(y,m,0).getDate(),cells=[];for(let i=0;i<42;i++){let day=i-off+1,dy=y,dm=m,muted=false;if(day<1){day=prevDays+day;dm=m-1;muted=true;if(dm<0){dm=11;dy--}}else if(day>days){day-=days;dm=m+1;muted=true;if(dm>11){dm=0;dy++}}const key=dayKey(dy,dm,day),has=d.some(e=>e.date===key);cells.push(`<button class="cal-day ${muted?'muted':''} ${has?'has':''} ${selected===key?'selected':''}" data-date="${key}">${day}</button>`)}$('[data-cal]').innerHTML=`<div class="cal-head"><button class="cal-nav" data-prev>‹</button><h2>${first.toLocaleDateString('de-DE',{month:'long',year:'numeric'})}</h2><button class="cal-nav" data-next>›</button></div><div class="cal-grid">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(x=>`<div class="cal-week">${x}</div>`).join('')}${cells.join('')}</div>`}
 function drawEvents(){const today=new Date().toISOString().slice(0,10);let list=d.filter(e=>selected?e.date===selected:e.date>=today).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('[data-list-title]').textContent=selected?new Date(selected+'T12:00:00').toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}):'Kommende Termine';$('[data-events]').innerHTML=list.map(e=>{const attendees=arr(e.attendees),cap=Number(e.capacity)||10,joined=attendees.includes(clientId),count=attendees.length,pct=Math.min(100,Math.round(count/cap*100));return `<article class="event-card"><span class="event-icon">${e.category==='Skilltraining'?'🫁':e.category==='Simulationstraining'?'❤️':'📅'}</span><span><span class="cat-pill">${esc(e.category||'Termin')}</span><h3>${esc(e.title)}</h3><div class="event-meta">🕒 ${esc(e.time)} · 📍 ${esc(e.location)}</div></span><span class="event-right"><div class="participants">👥 ${count}/${cap}</div><div class="progress"><span style="width:${pct}%"></span></div><button class="join-btn ${joined?'joined':''}" data-rsvp="${esc(e.id)}">${joined?'Teilnahme zurückziehen':'Teilnehmen'}</button></span></article>`}).join('')||'<div class="empty">Keine Termine</div>'}
 $('[data-main]').onclick=async e=>{if(e.target.closest('[data-prev]')){cursor.setMonth(cursor.getMonth()-1);selected='';drawCal();drawEvents();return}if(e.target.closest('[data-next]')){cursor.setMonth(cursor.getMonth()+1);selected='';drawCal();drawEvents();return}const day=e.target.closest('[data-date]');if(day){selected=day.dataset.date;const sd=new Date(selected+'T12:00:00');cursor=new Date(sd.getFullYear(),sd.getMonth(),1);drawCal();drawEvents();return}const r=e.target.closest('[data-rsvp]');if(r){r.disabled=true;const result=await toggleRsvp(r.dataset.rsvp,clientId);if(result&&result.events)d=result.events;else{const x=d.find(v=>v.id===r.dataset.rsvp);if(x){x.attendees=arr(x.attendees);const i=x.attendees.indexOf(clientId);if(i>=0)x.attendees.splice(i,1);else if(x.attendees.length<(Number(x.capacity)||10))x.attendees.push(clientId)}}drawCal();drawEvents()}};drawCal();drawEvents()}
async function editor(){
 const names=[['news','Aktuelles'],['articles','Literatur'],['abcde','ABCDE'],['differential','Diagnostik'],['skills','Skills'],['algorithms','Algorithmen'],['changes','Lehrmeinung'],['events','Termine'],['guide','Simulationstraining'],['materials','Materialien']];
 $('[data-main]').innerHTML=`<section class="page-banner"><h1>Redaktion</h1></section><div class="editor-tabs">${names.map((x,i)=>`<button class="editor-tab ${i?'':'active'}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div><section class="card editor-workspace" data-edit></section>`;
 async function draw(name){const d=name==='articles'?await articles():await get(name),box=$('[data-edit]');box.innerHTML=`<div class="editor-toolbar"><button class="btn primary" data-add>+ Neu</button><button class="btn" data-save>Speichern</button>${name==='articles'?'<button class="btn" data-doi-help>DOI-Hilfe</button>':''}</div><div data-items>${d.map((x,i)=>editCard(name,x,i)).join('')}</div>`;box.querySelector('[data-save]').onclick=async()=>{readForm(name,d,box);const ok=await save(name,d);alert(ok?'Gespeichert und synchronisiert.':'Lokal gespeichert. Worker-Sync nicht verfügbar.')};box.querySelector('[data-add]').onclick=()=>{d.unshift(blank(name));renderList()};if(box.querySelector('[data-doi-help]'))box.querySelector('[data-doi-help]').onclick=()=>open('DOI-Hilfe','<section class="overlay-section"><h3>DOI verwenden</h3><p class="news-text">DOI eintragen und beim Artikel „DOI-Daten abrufen“ auswählen. Titel, Autor:innen, Quelle, Jahr und Original-Link werden soweit verfügbar über Crossref ergänzt.</p></section>');function renderList(){box.querySelector('[data-items]').innerHTML=d.map((x,i)=>editCard(name,x,i)).join('')}box.onclick=async e=>{const del=e.target.closest('[data-del]');if(del){d.splice(+del.dataset.del,1);renderList();return}const lookup=e.target.closest('[data-doi-lookup]');if(lookup){const row=lookup.closest('[data-index]'),doi=$('[data-k="doi"]',row)?.value.trim();if(!doi)return alert('Bitte zuerst eine DOI eingeben.');lookup.disabled=true;lookup.textContent='Lade …';try{const r=await fetch(`https://api.crossref.org/works/${encodeURIComponent(doi)}`);if(!r.ok)throw new Error('DOI nicht gefunden');const m=(await r.json()).message;const set=(k,v)=>{const el=$(`[data-k="${k}"]`,row);if(el&&v!=null)el.value=v};set('title',Array.isArray(m.title)?m.title[0]:'');set('authors',(m.author||[]).map(a=>[a.given,a.family].filter(Boolean).join(' ')).join(', '));set('journal',Array.isArray(m['container-title'])?m['container-title'][0]:'');set('year',m.published?.['date-parts']?.[0]?.[0]||'');set('publisherUrl',m.URL||'');set('type',m.type||'');}catch(err){alert(err.message||'DOI konnte nicht geladen werden.')}finally{lookup.disabled=false;lookup.textContent='DOI-Daten abrufen'}}}
 }
 function f(x,k,l,type='input',opts=''){if(type==='textarea')return `<div class="field"><label>${l}</label><textarea data-k="${k}">${esc(Array.isArray(x[k])?x[k].join('\n'):(x[k]||''))}</textarea></div>`;if(type==='select')return `<div class="field"><label>${l}</label><select data-k="${k}">${opts}</select></div>`;return `<div class="field"><label>${l}</label><input data-k="${k}" ${type==='date'?'type="date"':''} value="${esc(x[k]??'')}"></div>`}
 function editCard(name,x,i){let fields='';if(name==='news')fields=f(x,'title','Titel')+f(x,'category','Kategorie')+f(x,'date','Datum','date')+f(x,'text','Text','textarea');else if(name==='events')fields=f(x,'title','Titel')+f(x,'date','Datum','date')+f(x,'time','Uhrzeit')+f(x,'location','Ort')+f(x,'category','Kategorie')+f(x,'capacity','Max. Teilnehmer')+f(x,'description','Beschreibung','textarea');else if(name==='changes')fields=f(x,'title','Titel')+f(x,'category','Kategorie')+f(x,'date','Datum','date')+f(x,'old','Bisher','textarea')+f(x,'new','Neu','textarea')+f(x,'source','Quelle');else if(name==='algorithms')fields=f(x,'title','Titel')+f(x,'icon','Symbol')+f(x,'category','Kategorie')+f(x,'stand','Stand')+f(x,'steps','Ablauf','textarea')+f(x,'source','Quelle');else if(name==='guide')fields=f(x,'title','Titel')+f(x,'icon','Symbol')+f(x,'steps','Schritte','textarea');else if(name==='materials')fields=f(x,'title','Titel')+f(x,'icon','Symbol')+f(x,'category','Kategorie')+f(x,'note','Beschreibung','textarea');else if(name==='abcde')fields=f(x,'key','Buchstabe')+f(x,'title','Titel')+f(x,'checks','Beurteilung','textarea')+f(x,'actions','Maßnahmen','textarea')+f(x,'pitfalls','Warnzeichen','textarea');else if(name==='differential')fields=f(x,'title','Leitsymptom')+f(x,'icon','Symbol / Emoji')+f(x,'causes','Ursachen','textarea')+f(x,'questions','Fragen','textarea')+f(x,'redflags','Red Flags','textarea');else if(name==='skills')fields=f(x,'name','Kategorie')+`<div class="field"><label>Skills (Skill | Punkt 1; Punkt 2)</label><textarea data-k="skills">${esc((x.skills||[]).map(s=>`${s.name} | ${(s.items||[]).join('; ')}`).join('\n'))}</textarea></div>`;else if(name==='articles')fields=`<div class="editor-grid two">${f(x,'title','Titel')}${f(x,'doi','DOI')}${f(x,'authors','Autor:innen')}${f(x,'journal','Journal / Quelle')}${f(x,'year','Jahr')}${f(x,'type','Dokumenttyp / Evidenztyp')}${f(x,'topics','Themen / Kategorien')}${f(x,'level','Zielgruppe (RS / RS-NFS / NFS)')}${f(x,'language','Sprache')}${f(x,'license','Lizenz')}${f(x,'read','Lesezeit')}${f(x,'access','Zugriff (oa / free / paywall)')}${f(x,'publisherUrl','Original-/Verlagslink')}${f(x,'freeUrl','Freier Volltext / Repository')}${f(x,'added','Hinzugefügt am','date')}</div>${f(x,'why','Warum lesenswert?','textarea')}<div class="editor-inline-actions"><button class="btn" type="button" data-doi-lookup>DOI-Daten abrufen</button></div>`;return `<details class="edit-card"><summary><span>${esc(x.title||x.name||x.key||'Neuer Eintrag')}</span><span>▾</span></summary><div class="edit-body" data-index="${i}">${fields}<button class="btn danger" data-del="${i}">Löschen</button></div></details>`}
 function readForm(name,d,box){$$('[data-index]',box).forEach(row=>{const x=d[+row.dataset.index];$$('[data-k]',row).forEach(el=>{const k=el.dataset.k;let v=el.value;if(['steps','checks','actions','pitfalls','causes','questions','redflags','topics'].includes(k))v=arr(v);if(k==='capacity')v=Number(v)||10;if(k==='skills')v=arr(v).map(line=>{let [n,items='']=line.split('|');return{name:n.trim(),items:arr(items)}});x[k]=v});if(!x.id)x.id=(x.title||x.name||'item').toLowerCase().replace(/[^a-z0-9äöü]+/gi,'-')+'-'+Date.now()})}
 function blank(n){if(n==='skills')return{name:'Neue Kategorie',skills:[]};if(n==='abcde')return{id:'x',key:'X',title:'Neuer Bereich',checks:[],actions:[],pitfalls:[]};if(n==='events')return{id:'event-'+Date.now(),title:'Neuer Termin',date:new Date().toISOString().slice(0,10),time:'18:00',location:'',category:'Simulationstraining',capacity:10,attendees:[]};if(n==='articles')return{id:'article-'+Date.now(),title:'Neuer Artikel',authors:'',journal:'',year:new Date().getFullYear(),doi:'',topics:[],type:'Fachartikel',read:'',access:'oa',level:'rs-nfs',language:'de',license:'',why:'',publisherUrl:'',freeUrl:'',featured:false,added:new Date().toISOString().slice(0,10),archived:false};return{id:'new-'+Date.now(),title:'Neuer Eintrag'}}
 $('.editor-tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;$$('.editor-tab').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.tab)};const hash=location.hash.replace('#','');draw(hash==='literatur'?'articles':'news')
}
async function init(){chrome();if(page==='home')return home();if(page==='news')return newsPage();if(page==='literature')return literature();if(page==='abcde')return abcdePage();if(page==='differential')return simpleCards('differential','Differentialdiagnostik','diff');if(page==='skills')return skills();if(page==='algorithms')return simpleCards('algorithms','Algorithmen & Leitlinien','alg');if(page==='changes')return simpleCards('changes','Lehrmeinungsänderungen','change');if(page==='events')return eventsPage();if(page==='guide')return simpleCards('guide','Simulationstraining','guide');if(page==='materials')return simpleCards('materials','Materialien','materials');if(page==='editor')return editor()}
window.addEventListener('DOMContentLoaded',init)
})();
