
(()=>{
const page=document.body.dataset.page||'home',API=(window.WISSEN_API_URL||'').replace(/\/$/,''),LS='ost1020-v26-',D=window.OST1020_DATA||{};let pin=sessionStorage.getItem('ost1020-pin')||'';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));const clone=v=>JSON.parse(JSON.stringify(v??[]));const arr=v=>Array.isArray(v)?v:String(v||'').split(/\n|;/).map(s=>s.trim()).filter(Boolean);
const cats={Lehrmeinung:'🔄',Leitlinie:'📋',Ausbildung:'🎓',Termin:'📅',VitaSim:'🎮',Organisation:'📢',Literatur:'📚'};
function chrome(){
 $('[data-menu-btn]').textContent='☰';$('[data-home-btn]').textContent='🏠';
 const groups=[['Wissen',[['literatur.html','📚','Literatur','literature'],['abcde.html','🩺','ABCDE','abcde'],['differential.html','🔎','Differentialdiagnostik','differential'],['skilltraining.html','🎓','Skilltraining','skills'],['algorithmen.html','📋','Algorithmen & Leitlinien','algorithms']]],['Aktuell',[['aktuelles.html','📢','Aktuelles','news'],['lehrmeinung.html','🔄','Lehrmeinungsänderungen','changes'],['termine.html','📅','Termine','events']]],['VitaSim',[['vitasim.html','🎮','VitaSim Anleitung','guide']]],['Weitere',[['materialien.html','📁','Materialien','materials'],['editor.html','🔐','Redaktion','editor']]]];
 document.body.insertAdjacentHTML('beforeend',`<div class="menu" data-menu><div class="shade" data-menu-close></div><aside class="menu-sheet"><div class="menu-head"><strong>OST 1020</strong><button class="close" data-menu-close>✕</button></div>${groups.map(g=>`<div class="nav-section">${g[0]}</div><nav class="nav">${g[1].map(x=>`<a href="${x[0]}" class="${page===x[3]?'active':''}"><span class="nav-icon">${x[1]}</span><span>${x[2]}</span><span>›</span></a>`).join('')}</nav>`).join('')}</aside></div><div class="overlay" data-overlay><div class="shade" data-overlay-close></div><section class="overlay-panel"><div class="overlay-head"><h2 data-overlay-title></h2><button class="close" data-overlay-close>✕</button></div><div class="overlay-body" data-overlay-body></div></section></div>`);
 $('[data-menu-btn]').onclick=()=>{$('[data-menu]').classList.add('show')};$$('[data-menu-close]').forEach(x=>x.onclick=()=>$('.menu').classList.remove('show'));$$('[data-overlay-close]').forEach(x=>x.onclick=()=>$('.overlay').classList.remove('show'));

}
function open(title,html){$('[data-overlay-title]').textContent=title;$('[data-overlay-body]').innerHTML=html;$('.overlay').classList.add('show')}
async function get(name){if(API){try{const r=await fetch(`${API}/content/${name}`,{cache:'no-store'});if(r.ok)return await r.json()}catch(e){}}try{const l=localStorage.getItem(LS+name);if(l)return JSON.parse(l)}catch(e){}return clone(D[name]||[])}
async function articles(){if(API){try{const r=await fetch(`${API}/articles`,{cache:'no-store'});if(r.ok)return await r.json()}catch(e){}}return clone(D.articles||[])}
async function save(name,data){localStorage.setItem(LS+name,JSON.stringify(data));if(API&&pin){try{const r=await fetch(`${API}/content/${name}`,{method:'PUT',headers:{'Content-Type':'application/json','X-Admin-Pin':pin},body:JSON.stringify(data)});return r.ok}catch(e){}}return false}
async function auth(p){if(API){try{const r=await fetch(`${API}/auth`,{method:'POST',headers:{'X-Admin-Pin':p}});return {ok:r.ok,server:true,status:r.status}}catch(e){return {ok:p==='1020',server:false,error:true}}}return {ok:p==='1020',server:false}}
function sec(t,list){return `<section class="overlay-section"><h3>${esc(t)}</h3><ul>${arr(list).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`}
function pageTitle(t){return `<h1 class="page-title">${esc(t)}</h1>`}
async function home(){const [news,arts,events,changes]=await Promise.all([get('news'),articles(),get('events'),get('changes')]);const today=new Date().toISOString().slice(0,10),next=(events||[]).filter(x=>x.date>=today).sort((a,b)=>a.date.localeCompare(b.date))[0],latest=(arts||[]).slice().sort((a,b)=>String(b.added||'').localeCompare(String(a.added||'')))[0],ch=(changes||[]).find(x=>x.active!==false);const active=(news||[]).filter(x=>x.active!==false).slice(0,4);$('[data-main]').innerHTML=`<section class="dashboard-hero"><div class="hero-kicker">OST 1020</div><h1>Wissenssammlung</h1><p>Wissen, Ausbildung, Termine und VitaSim an einem Ort.</p></section><section class="section"><div class="status-grid"><a class="status-card" href="aktuelles.html"><b>📢</b><div class="eyebrow">Aktuelles</div><strong>${active.length} Meldungen</strong></a><a class="status-card" href="termine.html"><b>📅</b><div class="eyebrow">Nächster Termin</div><strong>${next?esc(next.title):'Kein Termin'}</strong></a><a class="status-card" href="literatur.html"><b>📚</b><div class="eyebrow">Neu</div><strong>${latest?esc(latest.title):'Literatur'}</strong></a></div></section><section class="section"><div class="section-head"><h2>Aktuelles</h2><a href="aktuelles.html">Alle anzeigen</a></div><div class="news-list">${active.map(newsHtml).join('')||'<div class="empty">Keine Meldungen</div>'}</div></section><section class="section"><div class="section-head"><h2>Schnellzugriff</h2></div><div class="quick-grid">${[['literatur.html','📚','Literatur','lit'],['abcde.html','🩺','ABCDE','abc'],['differential.html','🔎','Diagnostik','diff'],['skilltraining.html','🎓','Skills','skill'],['algorithmen.html','📋','Algorithmen','alg'],['lehrmeinung.html','🔄','Lehrmeinung','change'],['termine.html','📅','Termine','term'],['vitasim.html','🎮','VitaSim Anleitung','guide']].map(x=>`<a class="quick-card ${x[3]}" href="${x[0]}"><span class="emoji">${x[1]}</span><strong>${x[2]}</strong></a>`).join('')}</div></section>${next?`<section class="section"><div class="section-head"><h2>Nächster Termin</h2><a href="termine.html">Termine</a></div><a class="row-card" href="termine.html"><span class="row-icon">📅</span><span><strong>${esc(next.title)}</strong><small>${esc(next.date)} · ${esc(next.time)} · ${esc(next.location)}</small></span><span class="arrow">›</span></a></section>`:''}`}
function newsHtml(n){const c=n.category||'Organisation';return `<article class="news-item"><span class="news-icon">${cats[c]||'📢'}</span><div><span class="cat-pill cat-${c.toLowerCase().replace(/ä/g,'a')}">${esc(c)}</span><h3>${esc(n.title)}</h3><div class="news-meta">${esc(n.date||'')}</div><div class="news-text">${esc(n.text||'')}</div></div><span class="arrow">›</span></article>`}
async function newsPage(){const d=await get('news');$('[data-main]').innerHTML=pageTitle('Aktuelles')+`<section class="card"><div class="searchbar"><select data-filter><option value="all">Alle Kategorien</option>${[...new Set(d.map(x=>x.category||'Organisation'))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="news-list" data-list></div></section>`;const draw=()=>{$('[data-list]').innerHTML=d.filter(x=>$('[data-filter]').value==='all'||(x.category||'Organisation')===$('[data-filter]').value).map(newsHtml).join('')};$('[data-filter]').onchange=draw;draw()}
async function literature(){const arts=await articles();const defs=[['Reanimation','⚡',['Reanimation','Kreislaufstillstand']],['Simulation & Debriefing','🎯',['Simulation','Debriefing','Ausbildung']],['CRM & Human Factors','👥',['CRM','Human Factors','Entscheidungsfindung']],['Neurologie / Schlaganfall','🧠',['Neurologie','Schlaganfall']],['Qualität & Sicherheit','🛡️',['Qualität','Patientensicherheit','System']],['Critical Care','🫁',['Critical Care','Diagnostik']],['Pharmakologie & Schmerz','💊',['Pharmakologie','Schmerz']],['HEMS & Präklinik','🚁',['HEMS','Versorgung','Österreich']]];let groups=defs.map((x,i)=>({id:'g'+i,title:x[0],icon:x[1],items:arts.filter(a=>arr(a.topics).some(t=>x[2].includes(t)))})).filter(x=>x.items.length);$('[data-main]').innerHTML=pageTitle('Literatursammlung')+`<section class="card"><div class="searchbar"><input data-q placeholder="Artikel oder Thema suchen …"><select data-f><option value="all">Alle Themen</option>${groups.map(g=>`<option value="${g.id}">${g.title}</option>`).join('')}</select></div><div class="list" data-list></div></section>`;function draw(){let q=$('[data-q]').value.toLowerCase(),f=$('[data-f]').value;let v=groups.filter(g=>(f==='all'||g.id===f)&&(!q||g.title.toLowerCase().includes(q)||g.items.some(a=>JSON.stringify(a).toLowerCase().includes(q))));$('[data-list]').innerHTML=v.map(g=>`<button class="row-card" data-id="${g.id}"><span class="row-icon">${g.icon}</span><span><strong>${esc(g.title)}</strong><small>${g.items.length} Artikel</small></span><span class="arrow">›</span></button>`).join('')}$('[data-q]').oninput=draw;$('[data-f]').onchange=draw;$('[data-list]').onclick=e=>{let b=e.target.closest('[data-id]');if(!b)return;let g=groups.find(x=>x.id===b.dataset.id);open(g.title,g.items.map(a=>`<section class="overlay-section"><h3>${esc(a.title)}</h3><div class="news-meta">${esc(a.journal||'')} ${a.year?'· '+a.year:''}</div><div class="news-text">${esc(a.why||'')}</div>${a.freeUrl||a.publisherUrl?`<a class="btn primary" style="display:inline-flex;align-items:center;margin-top:9px" target="_blank" href="${esc(a.freeUrl||a.publisherUrl)}">Artikel öffnen</a>`:''}</section>`).join(''))};draw()}
async function simpleCards(name,title,mode){const d=await get(name);$('[data-main]').innerHTML=pageTitle(title)+`<section class="card"><div class="list">${d.map((x,i)=>`<button class="row-card" data-i="${i}"><span class="row-icon">${esc(x.icon||x.key||'•')}</span><span><strong>${esc(x.title||x.name)}</strong><small>${esc(x.category||x.subtitle||'')}</small></span><span class="arrow">›</span></button>`).join('')}</div></section>`;$('[data-main]').onclick=e=>{let b=e.target.closest('[data-i]');if(!b)return;let x=d[+b.dataset.i],html='';if(mode==='abc')html=sec('Beurteilung',x.checks)+sec('Maßnahmen',x.actions)+sec('Häufige Fehler',x.pitfalls);else if(mode==='diff')html=sec('Mögliche Ursachen',x.causes)+sec('Wichtige Fragen',x.questions)+sec('Red Flags',x.redflags);else if(mode==='alg')html=sec('Ablauf',x.steps)+`<section class="overlay-section"><h3>Stand / Quelle</h3><div class="news-text">${esc(x.stand||'')}<br>${esc(x.source||'')}</div></section>`;else if(mode==='change')html=`<section class="overlay-section"><h3>Bisher</h3><div class="news-text">${esc(x.old)}</div></section><section class="overlay-section"><h3>Neu</h3><div class="news-text">${esc(x.new)}</div></section><section class="overlay-section"><h3>Quelle</h3><div class="news-text">${esc(x.source||'')}</div></section>`;else if(mode==='guide')html=sec('Schritte',x.steps);else if(mode==='materials')html=`<section class="overlay-section"><h3>${esc(x.category||'Material')}</h3><div class="news-text">${esc(x.note||'')}</div></section>`;open(x.title||x.name,html)}}
async function abcdePage(){
 const d=await get('abcde');
 const tone=['a-red','b-blue','c-green','d-purple','e-orange'];
 const labels={A:'Atemweg',B:'Atmung',C:'Kreislauf',D:'Neurologie',E:'Ganzkörper'};
 $('[data-main]').innerHTML=pageTitle('ABCDE-Schema')+`<section class="abcde-shell"><div class="abcde-rail">${d.map((x,i)=>`<button class="abcde-step ${tone[i]||'b-blue'}" data-abc-i="${i}"><span class="abcde-key">${esc(x.key||'')}</span><span class="abcde-copy"><strong>${esc(x.title||'')}</strong><small>${esc(labels[x.key]||'')}</small></span><span class="abcde-arrow">›</span></button>`).join('')}</div><div class="abcde-note"><strong>ABCDE</strong><span>Prioritäten erkennen · behandeln · erneut beurteilen</span></div></section>`;
 $('[data-main]').onclick=e=>{const b=e.target.closest('[data-abc-i]');if(!b)return;const x=d[+b.dataset.abcI];open(`${x.key} · ${x.title}`,`<div class="abcde-overlay-head"><span class="abcde-big-key ${tone[+b.dataset.abcI]||'b-blue'}">${esc(x.key)}</span><div><strong>${esc(labels[x.key]||x.title)}</strong><small>${esc(x.title)}</small></div></div>${sec('Beurteilung',x.checks)}${sec('Maßnahmen',x.actions)}${sec('Häufige Fehler',x.pitfalls)}`)};
}
async function skills(){const d=await get('skills');$('[data-main]').innerHTML=pageTitle('Skilltraining')+`<section class="card"><div class="list">${d.map((g,i)=>`<button class="row-card" data-g="${i}"><span class="row-icon">${['🚑','🧑‍⚕️','🩹'][i]||'🎓'}</span><span><strong>${esc(g.name)}</strong><small>${g.skills.length} Skills</small></span><span class="arrow">›</span></button>`).join('')}</div></section>`;$('[data-main]').onclick=e=>{let b=e.target.closest('[data-g]');if(!b)return;let g=d[+b.dataset.g];open(g.name,g.skills.map(s=>`<button class="row-card" data-skill="${esc(s.name)}" style="width:100%"><span class="row-icon">🎓</span><span><strong>${esc(s.name)}</strong><small>${s.items.length} Punkte</small></span><span class="arrow">›</span></button>`).join(''));setTimeout(()=>{$$('[data-skill]').forEach(btn=>btn.onclick=()=>{let s=g.skills.find(x=>x.name===btn.dataset.skill);open(s.name,sec('Checkpunkte',s.items))})},0)}}
async function eventsPage(){const d=await get('events');const now=new Date(),year=now.getFullYear(),month=now.getMonth();let first=new Date(year,month,1),days=new Date(year,month+1,0).getDate(),offset=(first.getDay()+6)%7,slots=[];for(let i=0;i<offset;i++)slots.push('');for(let day=1;day<=days;day++)slots.push(day);$('[data-main]').innerHTML=pageTitle('Termine')+`<section class="calendar"><div class="cal-head"><h2>${first.toLocaleDateString('de-DE',{month:'long',year:'numeric'})}</h2><span>📅</span></div><div class="cal-grid">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(x=>`<div class="cal-week">${x}</div>`).join('')}${slots.map(day=>{if(!day)return'<div></div>';let ds=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,has=d.some(e=>e.date===ds);return`<button class="cal-day ${has?'has':''}" data-date="${ds}">${day}</button>`}).join('')}</div></section><section class="section"><div class="section-head"><h2>Kommende Termine</h2></div><div class="list">${d.sort((a,b)=>a.date.localeCompare(b.date)).map((e,i)=>`<button class="row-card" data-event="${i}"><span class="row-icon">📅</span><span><strong>${esc(e.title)}</strong><small>${esc(e.date)} · ${esc(e.time)} · ${esc(e.location)}</small></span><span class="arrow">›</span></button>`).join('')}</div></section>`;$('[data-main]').onclick=e=>{let b=e.target.closest('[data-event]');if(b){let x=d[+b.dataset.event];open(x.title,`<section class="overlay-section"><h3>${esc(x.date)} · ${esc(x.time)}</h3><div class="news-text">${esc(x.location)}</div></section><section class="overlay-section"><h3>${esc(x.category)}</h3><div class="news-text">${esc(x.description||'')}</div></section>`);return}let day=e.target.closest('[data-date]');if(day){let es=d.filter(x=>x.date===day.dataset.date);if(es.length)open(day.dataset.date,es.map(x=>`<section class="overlay-section"><h3>${esc(x.title)}</h3><div class="news-meta">${esc(x.time)} · ${esc(x.location)}</div></section>`).join(''))}}}
async function editor(){
 if(!pin){
   $('[data-main]').innerHTML=pageTitle('Redaktion')+`<section class="pin-box"><div class="pin-lock">🔐</div><h2>Redaktion entsperren</h2><p>Bitte Redaktions-PIN eingeben.</p><input data-pin-input type="password" inputmode="numeric" autocomplete="current-password" placeholder="PIN"><div class="actions"><button class="btn primary" data-pin-submit>Öffnen</button><a class="btn" href="index.html">Abbrechen</a></div><div class="pin-status" data-pin-status></div></section>`;
   const submit=async()=>{const p=$('[data-pin-input]').value.trim();if(!p)return;const r=await auth(p);if(r.ok){pin=p;sessionStorage.setItem('ost1020-pin',p);editor();return} $('[data-pin-status]').innerHTML=r.server?`PIN wurde vom Worker abgelehnt. Prüfe <b>ADMIN_PIN_SHA256</b> im Cloudflare Worker.`:'PIN nicht korrekt.'};
   $('[data-pin-submit]').onclick=submit;$('[data-pin-input]').onkeydown=e=>{if(e.key==='Enter')submit()};return;
 }
 const names=[['news','Aktuelles'],['articles','Literatur'],['abcde','ABCDE'],['differential','Diagnostik'],['skills','Skills'],['algorithms','Algorithmen'],['changes','Lehrmeinung'],['events','Termine'],['guide','VitaSim Anleitung'],['materials','Materialien']];$('[data-main]').innerHTML=pageTitle('Redaktion')+`<div class="editor-tabs">${names.map((x,i)=>`<button class="editor-tab ${i?'':'active'}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div><section class="card" data-edit></section>`;async function draw(name){let d=name==='articles'?await articles():await get(name);let box=$('[data-edit]');box.innerHTML=`<div class="actions" style="margin-bottom:10px"><button class="btn primary" data-add>+ Neu</button><button class="btn" data-save>Speichern</button></div><div data-items>${d.map((x,i)=>editCard(name,x,i)).join('')}</div>`;box.dataset.name=name;box._data=d;box.querySelector('[data-save]').onclick=async()=>{readForm(name,d,box);let ok=await save(name,d);alert(ok?'Gespeichert und synchronisiert.':'Lokal gespeichert. Worker-Sync nicht verfügbar.')};box.querySelector('[data-add]').onclick=()=>{d.unshift(blank(name));draw(name)};box.onclick=e=>{let del=e.target.closest('[data-del]');if(del){d.splice(+del.dataset.del,1);draw(name)}}}
 function editCard(name,x,i){let fields='';const f=(k,l,type='input')=>type==='textarea'?`<div class="field"><label>${l}</label><textarea data-k="${k}">${esc(arr(x[k]).join('\n')||x[k]||'')}</textarea></div>`:`<div class="field"><label>${l}</label><input data-k="${k}" value="${esc(x[k]||'')}"></div>`;if(name==='news')fields=f('title','Titel')+f('category','Kategorie')+f('date','Datum')+f('text','Text','textarea');else if(name==='events')fields=f('title','Titel')+f('date','Datum')+f('time','Uhrzeit')+f('location','Ort')+f('category','Kategorie')+f('description','Beschreibung','textarea');else if(name==='changes')fields=f('title','Titel')+f('category','Kategorie')+f('date','Datum')+f('old','Bisher','textarea')+f('new','Neu','textarea')+f('source','Quelle');else if(name==='algorithms')fields=f('title','Titel')+f('icon','Symbol')+f('category','Kategorie')+f('stand','Stand')+f('steps','Ablauf – eine Zeile pro Schritt','textarea')+f('source','Quelle');else if(name==='guide')fields=f('title','Titel')+f('icon','Symbol')+f('steps','Schritte','textarea');else if(name==='materials')fields=f('title','Titel')+f('icon','Symbol')+f('category','Kategorie')+f('note','Beschreibung','textarea');else if(name==='abcde')fields=f('key','Buchstabe')+f('title','Titel')+f('checks','Beurteilung','textarea')+f('actions','Maßnahmen','textarea')+f('pitfalls','Fehler','textarea');else if(name==='differential')fields=f('title','Leitsymptom')+f('causes','Ursachen','textarea')+f('questions','Fragen','textarea')+f('redflags','Red Flags','textarea');else if(name==='skills')fields=f('name','Kategorie')+`<div class="field"><label>Skills (Format: Skill | Punkt 1; Punkt 2)</label><textarea data-k="skills">${esc((x.skills||[]).map(s=>`${s.name} | ${(s.items||[]).join('; ')}`).join('\n'))}</textarea></div>`;else if(name==='articles')fields=f('title','Titel')+f('authors','Autor:innen')+f('journal','Quelle')+f('year','Jahr')+f('topics','Themen')+f('why','Warum relevant?','textarea')+f('freeUrl','Link');return `<details class="edit-card"><summary>${esc(x.title||x.name||x.key||'Neuer Eintrag')}<span>▾</span></summary><div class="edit-body" data-index="${i}">${fields}<button class="btn danger" data-del="${i}">Löschen</button></div></details>`}
 function readForm(name,d,box){$$('[data-index]',box).forEach(row=>{let x=d[+row.dataset.index];$$('[data-k]',row).forEach(el=>{let k=el.dataset.k,v=el.value;if(['steps','checks','actions','pitfalls','causes','questions','redflags','topics'].includes(k))v=arr(v);if(k==='skills')v=arr(v).map(line=>{let [n,items='']=line.split('|');return{name:n.trim(),items:arr(items)}});x[k]=v});if(!x.id)x.id=(x.title||x.name||'item').toLowerCase().replace(/[^a-z0-9äöü]+/gi,'-')+'-'+Date.now()})}
 function blank(n){if(n==='skills')return{name:'Neue Kategorie',skills:[]};if(n==='abcde')return{id:'x',key:'X',title:'Neuer Bereich',checks:[],actions:[],pitfalls:[]};return{id:'new-'+Date.now(),title:'Neuer Eintrag'}}
 $('.editor-tabs').onclick=e=>{let b=e.target.closest('[data-tab]');if(!b)return;$$('.editor-tab').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.tab)};draw('news')}
async function init(){chrome();if(page==='home')return home();if(page==='news')return newsPage();if(page==='literature')return literature();if(page==='abcde')return abcdePage();if(page==='differential')return simpleCards('differential','Differentialdiagnostik','diff');if(page==='skills')return skills();if(page==='algorithms')return simpleCards('algorithms','Algorithmen & Leitlinien','alg');if(page==='changes')return simpleCards('changes','Lehrmeinungsänderungen','change');if(page==='events')return eventsPage();if(page==='guide')return simpleCards('guide','VitaSim Anleitung','guide');if(page==='materials')return simpleCards('materials','Materialien','materials');if(page==='editor')return editor()}
window.addEventListener('DOMContentLoaded',init)
})();
